# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef66a167ad1570d9876af6b7ed5a6c5583065458b25ed863617f70b871cd51187e721b8cb225bc7c408b357585fa52ac976cec447879b78690b6224a601c324

test:
  secret_key_base: 2efaa7b7aab8e6105927c3a4d4817899624bd5843c67c70d905f34d421627dd2951fc1198d18dc2a656eacc61e9f0a88dda21cc0328337d111fd42ab2f430a24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
